sudo: false
language: node_js
node_js:
  - 8.1.2
install:
  - yarn install
notifications:
  email: false
script:
  - yarn build
  - yarn test:ci
after_success:
  - node node_modules/.bin/codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
